source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Graffiti' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Graffiti
  pod 'Alamofire', '~> 4.3'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'Google/SignIn'

  target 'GraffitiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GraffitiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
